# .circleci/config.yml
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: go mod download

      - run:
          name: Run Tests with Coverage
          command: |
            mkdir -p test_reports
            go test -v -coverprofile=coverage.out ./...
            go tool cover -html=coverage.out -o test_reports/coverage.html

      - store_artifacts:
          path: test_reports
          destination: coverage

      - run:
          name: Run Static Analysis
          command: |
            go vet ./...
            go fmt ./...
            # Optionally add golint or staticcheck
            # go install golang.org/x/lint/golint@latest
            # golint ./...

  docker_build:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t suryakang/sys-monitor:${CIRCLE_SHA1} .
      - run:
          name: Push Docker Image
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push suryakang/sys-monitor:${CIRCLE_SHA1}

workflows:
  build_and_deploy:
    jobs:
      - build
      - docker_build:
          requires:
            - build
